#!/bin/sh

PDIR=`pwd`
rm -rf /tmp/${PNAME}
mkdir /tmp/${PNAME} && cp -r . /tmp/${PNAME} && \
cd /tmp && (find ${PNAME}/ -name .svn | xargs rm -rf) && \
tar fcz "${PDIR}/../${PNAME}_${VER}.tar.gz" ${PNAME}
